version: '2'
services:
  cocoji-app:
    image: cocoji
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://cocoji-mysql:3306/cocoji?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
      - SPRING_DATA_JEST_URI=http://cocoji-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://cocoji-elasticsearch:9200
    ports:
      - 8080:8080
  cocoji-mysql:
    extends:
      file: mysql.yml
      service: cocoji-mysql
  cocoji-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: cocoji-elasticsearch
